### PR TITLE
Docker Build and Run from container

### PR DESCRIPTION
**Pull request by calh**
Hi,

I'm working with an older Ubuntu 18 system.  All of the system packages are old enough that it's difficult to get Bambu Studio to compile and run.  I've set up a Dockerfile and some helper scripts to build and run Bambu Studio from within the Docker container.

The `DockerRun.sh` script bind-mounts the user's home directory inside the container and passes enough X information to run the application.  

I'd be glad to document a basic step-by-step on your wiki, but I can't find where your source is for that documentation.

Pretty much all you have to do is:

```
$ ./DockerBuild.sh
   # Wait a really long time
$ ./DockerRun.sh
```

Optionally, you can pass arguments to the `DockerRun.sh` to pass on to the `bambu-studio` binary with something like

```
$ ./DockerRun.sh /home/myuser/mymodel.stl
```

### CODE REVIEW

**Comment by calh** [comment]
As a side note, I just ordered an X1C and am waiting for it to ship.  So, I don't have a way to actually test this other than slicing and saving a 3MF file.

**Comment by calh** [comment]
Yeah, I just took a copy of the `Containerfile` to make the `Dockerfile`.  I didn't want to mess with any of your existing CI/CD pipeline or anything else.  If you do want me to merge my additions over to the `Containerfile` however, I think my additions should be pretty safe.  I can adjust my build script to use that instead of `Dockerfile` too. 

Anyway, I'm open to whatever you want me to do, just let me know!

**Comment by fang64** [comment]
@calh I made a modification to the BuildLinux.sh script that patches AppImage builder so it'll work in Docker now. I check to see if it's in a container or not. You should be able to just run the script since my PR got pulled in. I am using act (github actions local runner tester) and it's leveraging docker.

**Comment by calh** [comment]
@fang64, I did experiment with the `--appimage-extract-and-run` flag as well.  It worked fine and all, but the main issues I'm addressing in this PR are:

* Installing the locale packages and setting the locale
* Setting the $SSL_CERT_FILE environment variable
* Running Bambu as the same UID as your docker host user.  It's easier to share files to your docker host
* Giving privileged permissions to the container for access to the video card
* Running with host networking for communication to the host's localhost dbus.  (And, easier communication over wifi to the printer)
* Also, running the `bambu-studio` binary directly is less disk thrashing on startup, since you have to unpack the whole AppImage.

**Comment by fang64** [comment]
@calh That was in context to building Bambu-Studio, I see that you are using this to run the application. that change was mostly to use Docker as a Github Action Runner for the AppImage. Also Normally AppImages are mounted with Fuse, so there shouldn't be disk thrashing since it's just a mounted filesystem. Although in this context, unless you are using Red Hat's Podman you wont have Fuse available in the container environment for AppImage to use.

**Comment by lanewei120** [comment]
thanks for doing this

**Comment by calh** [comment]
@lanewei120, you're welcome!  Do you want me to add documentation to your wiki pages?

**Comment by lanewei120** [comment]
> @lanewei120, you're welcome! Do you want me to add documentation to your wiki pages?

Sure, It will be really helpful to us~

**Comment by calh** [comment]
@lanewei120, I've never contributed to a github wiki source before...  it looks like I can clone `https://github.com/bambulab/BambuStudio.wiki.git`, but how do I fork it and publish a PR to it?  Or what is the CI process you'd like me to do with it?

**Comment by calh** [comment]
@lanewei120, I _think_ maybe I figured this out... but yeesh, github doesn't make this easy.

Try pulling my forked wiki repo:  `https://github.com/calh/BambuStudio.wiki.git` and look for the commit 

```commit 27d86fa47b3c0b9346d7b854322fcb32c6162adc
Author: Cal Heldenbrand <cal@fbsdata.com>
Date:   Fri Mar 3 12:02:54 2023 -0600

    Add Docker Run documentation
```

**Comment by deftdawg** [comment]
Generically the fastest way to submit a small patch to a repo is:

Go to the github page of the source file or wiki page you want to patch, hit edit (pencil), make changes, add a commit message...  Github will fork the repo for you and ask if you want to make a pull request.  Fill in pull request details and submit.

**Comment by calh** [comment]
@deftdawg, it's easy for source repos, but the wiki repos seem completely different and horrible.

https://gist.github.com/larrybotha/10650410

https://stackoverflow.com/a/56480628

**Comment by lanewei120** [comment]
> @lanewei120, I _think_ maybe I figured this out... but yeesh, github doesn't make this easy.
> 
> Try pulling my forked wiki repo: `https://github.com/calh/BambuStudio.wiki.git` and look for the commit
> 
> ```
> Author: Cal Heldenbrand <cal@fbsdata.com>
> Date:   Fri Mar 3 12:02:54 2023 -0600
> 
>     Add Docker Run documentation
> ```

I can find the page newly created
image
and no contents on this page

**Comment by calh** [comment]
Oh derp, I completely missed adding the file to my commit!  Here you go @lanewei120 

https://github.com/calh/BambuStudio/wiki/Docker-Run-Guide

The commit is:

```
commit de85175861e26463baac970f880fafa5d291a63a 
Author: Cal Heldenbrand <cal@fbsdata.com>
Date:   Sat Mar 4 10:00:42 2023 -0600

    Forgot to add the Docker Run file!
```

**Comment by lanewei120** [comment]
ok, just picked from your fork

image

thanks for doing this

**Pull request merged**
