### PR TITLE
deps: Update wxWidgets build options

### PR DESCRIPTION
**Pull request by hadess**

### CODE REVIEW

**Review by bambu123 — COMMENTED** [review]
<html>
<body>

wxUSE_LIBMSPACK | Use libmspack library.
-- | --



</body>
</html>

**Comment by hadess** [comment]
> wxUSE_XPM | Enable XPM reader for wxImage and wxBitmap classes. -- | -- wxUSE_XPM Enable XPM reader for [wxImage](https://docs.wxwidgets.org/latest/classwx_image.html) and [wxBitmap](https://docs.wxwidgets.org/latest/classwx_bitmap.html) classes.

`wxUSE_XPM` isn't the same as `wxUSE_LIBXPM`.

> wxUSE_LIBMSPACK | Use libmspack library. -- | --

I don't understand that comment.

BambuStudio seems to expect wxWidgets to be build with this option, but doesn't force it on when building wxWidgets. So one could potentially build all the way to BambuStudio and not be able to finish building because wxWidgets wasn't build with mspack support enabled.

If libmspack isn't actually needed (it looks like it actually isn't...), I can remove that commit from the PR, and remove it from the required build packages instead.

**Comment by lanewei120** [comment]
why remove this one ”-DCMAKE_DEBUG_POSTFIX:STRING=“

**Comment by hadess** [comment]
> why remove this one ”-DCMAKE_DEBUG_POSTFIX:STRING=“

Because nothing uses it, as mentioned in the cmake warning output that's in the commit message.

**Comment by hadess** [comment]
> If libmspack isn't actually needed (it looks like it actually isn't...), I can remove that commit from the PR, and remove it from the required build packages instead.

I've disabled the mspack requirement now.

**Comment by lanewei120** [comment]
CMAKE_DEBUG_POSTFIX is used on other platform, such as windows
there is no warnings on windows
image

**Comment by hadess** [comment]
> CMAKE_DEBUG_POSTFIX is used on other platform, such as windows

OK, I've removed that bit.

**Comment by lanewei120** [comment]
thanks for doing this

**Pull request merged**
