### PR TITLE
Fix missing build dependency (bc) in Dockerfile

### PR DESCRIPTION
**Pull request by penguineer**
The build was canceled due to missing bc. This PR adds the `bc` package to the build environment.

```
> [ 9/12] RUN ./BuildLinux.sh -d:
0.383 FOUND_GTK3=ii  libgtk-3-0:amd64    3.24.33-1ubuntu2.2 amd64        GTK graphical user interface library
0.383 ii  libgtk-3-bin        3.24.33-1ubuntu2.2 amd64        programs for the GTK graphical user interface library
0.383 ii  libgtk-3-common     3.24.33-1ubuntu2.2 all          common files for the GTK graphical user interface library
0.383 ii  libgtk-3-dev:amd64  3.24.33-1ubuntu2.2 amd64        development files for the GTK library
0.383 un  libgtk-3-doc        <none>             <none>       (no description available)
0.383 Changing date in version...
0.385 done
0.393 ./BuildLinux.sh: line 122: bc: command not found
------

3 warnings found (use --debug to expand):
- LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 2)
- WorkdirRelativePath: Relative workdir "BambuStudio" can have unexpected results if the base image changes (line 63)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 76)
Dockerfile:70
--------------------
68 |
69 |     # Build dependencies in ./deps
70 | >>> RUN ./BuildLinux.sh -d
71 |
72 |     # Build slic3r
--------------------
ERROR: failed to solve: process "/bin/sh -c ./BuildLinux.sh -d" did not complete successfully: exit code: 127
```

The build is successful when `bc` is available.

### CODE REVIEW

**Comment by penguineer** [comment]
This is interesting, as it worked flawless for me. I will, of course, have a look! Thank you for testing!

**Comment by penguineer** [comment]
> ```
> ./BuildLinux.sh: line 122: bc: command not found
> Error: error building at STEP "RUN ./BuildLinux.sh -d ${BUILD_LINUX_EXTRA_ARGS}": error while running runtime: exit status 127
> Error: Process completed with exit code 125.
> ```
> 
> Still have the bc command loss problem. I've made a lot of changes to BuildLinux.sh recently, and the dockerfile needs to follow suit with some adjustments.

Unfortunately, I cannot reproduce that. I am running from a fresh environment and Docker Build with the script `DockerBuild.sh` runs fine from my branch, but throws the error on master.

**Comment by penguineer** [comment]
I just realized: The action calles `BuildLinux.sh` directly and apparently this still fails. It might be because `bc` is not available on the Ubuntu Runner either.

**Comment by MackBambu** [comment]
> I just realized: The action calles `BuildLinux.sh` directly and apparently this still fails. It might be because `bc` is not available on the Ubuntu Runner either.

It works fine on Ubuntu runner and I don't understand why the command is lost in a docker environment, even if I reinstall it. I'm already planning to submit a version that removes the bc command.
https://github.com/MackBambu/BambuStudio/blob/cb28fa6ff99ea15186b403563a50bf8af2603188/BuildLinux.sh#L122

**Comment by penguineer** [comment]
> I'm already planning to submit a version that removes the bc command. https://github.com/MackBambu/BambuStudio/blob/cb28fa6ff99ea15186b403563a50bf8af2603188/BuildLinux.sh#L122

@MackBambu  In this case, does it make sense to put further work into this PR?

**Comment by MackBambu** [comment]
> @MackBambu In this case, does it make sense to put further work into this PR?

no need

**Comment by MackBambu** [comment]
> @MackBambu In this case, does it make sense to put further work into this PR?

no need

**Pull request closed without merging**
