### PR TITLE
Add filament usage stats to generated GCode files

### LINKED ISSUE #3072: Missing properties from sliced files
**Is your feature request related to a problem? Please describe.**
I'm building a business using Bambu Printers, and I want to automatize the slicing process. However there are a few properties missing from the sliced gcode output which was available in the upstream repository of Bambu Studio and are required for me to properly calculate the prices of prints.

**Describe the solution you'd like**
I would like to get back the following proprties in the GCode output (header comments):
- filament used [mm] 
- filament used [cm3]

**Describe alternatives you've considered**
For me, I don't see any alternatives. I'm forced to use Prusa Slicer (the upstream repository) until this gets resolved, which means I need to convert config files, etc. etc.

### PR DESCRIPTION
**Pull request by THE-SIMPLE-MARK**
This feature is available in Slic3r and Prusa slicer, however it seems that this functionality has never been migrated to Bambu Studio. This PR aims to do exactly that.

This would fix #3072.

### To-do list
- [x] Add placeholders for properties
- [ ] Fill in placeholders with actual data in post processing (in `process_gcode_line`)

### CODE REVIEW

**Comment by THE-SIMPLE-MARK** [comment]
@XunZhangBambu This is the new PR. I have added the placeholders, however I have no clue about how to even begin on filling in the placeholders due to my very-very limited skills in c++. Can you help me out?

You should be able to edit my fork if you're set as contributor to this repository, otherwise please notify me and I'll give you access manually.

**Comment by XunZhangBambu** [comment]
Okay, I will fix it and submit it to your repository.

**Comment by XunZhangBambu** [comment]
I have completed a simple version, but I don't have the permission to push to your repository

**Comment by THE-SIMPLE-MARK** [comment]
> I have completed a simple version, but I don't have the permission to push to your repository

Just sent you an invite.

**Comment by XunZhangBambu** [comment]
@THE-SIMPLE-MARK  I have submitted my changes to the filament branch. You take a look. It's just a relatively basic implementation, and the code is not quite elegant enough.

**Comment by THE-SIMPLE-MARK** [comment]
> @THE-SIMPLE-MARK I have submitted my changes to the filament branch. You take a look. It's just a relatively basic implementation, and the code is not quite elegant enough.

Awesome, I'm gonna build it and test it out. I made one tiny mistake though and I accidentally made this PR's origin branch master so I'm going to have to put your changes into master so I don't have to make another PR 😅

**Comment by XunZhangBambu** [comment]
@THE-SIMPLE-MARK  Yes, I have only included the weight of the filaments . As I mentioned, this is just a basic version . Personally I think such handling disrupts the original code structure. I will continue to refine the code later

**Comment by THE-SIMPLE-MARK** [comment]
> @THE-SIMPLE-MARK Yes, I have only included the weight of the filaments . As I mentioned, this is just a basic version . Personally I think such handling disrupts the original code structure. I will continue to refine the code later

Alrighty. Should I close this PR and open up another one from the correct branch or are you fine with working on master?

**Comment by XunZhangBambu** [comment]
I prefer opening up another one from the new patch since uncommenting the original code doesn't provide acurrate filament consumption. Also, I would like to know which statics you need and in what format.

**Comment by THE-SIMPLE-MARK** [comment]
> I prefer opening up another one from the new patch since uncommenting the original code doesn't provide acurrate filament consumption. Also, I would like to know which statics you need and in what format.

Alright I'm gonna do that. I'll ping you in the new PR, it will have every info we'll need in the description.

**Pull request closed without merging**
