### PR TITLE
additional appimage job for ubuntu 20.04

### PR DESCRIPTION
**Pull request by abhijitmajumdar**
added a copy of the job to build with ubuntu 20.04 builder image to define correct glib versions. Also see discussion in https://github.com/bambulab/BambuStudio/issues/1667

### CODE REVIEW

**Comment by lanewei120** [comment]
thanks for doing this

**Comment by nkhedekar** [comment]
The build seems to have failed: https://github.com/bambulab/BambuStudio/actions/runs/5487881208/jobs/10030442286#step:4:37212

**Comment by lanewei120** [comment]
seems failed due to gmp downloading failed
already reported a bug to github
https://github.com/actions/runner-images/issues/7901

**Comment by lanewei120** [comment]
I just submitted a workaround to fix the gmp downloading issue
however found the space not engouth issue with this building
(https://github.com/bambulab/BambuStudio/actions/runs/5531290662/jobs/10091787156)

Error: error committing container for step {Env:[BUILD_LINUX_EXTRA_ARGS=-r PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[./BuildLinux.sh -d ${BUILD_LINUX_EXTRA_ARGS}] Flags:[] Attrs:map[] Message:RUN ./BuildLinux.sh -d ${BUILD_LINUX_EXTRA_ARGS} Original:RUN ./BuildLinux.sh -d ${BUILD_LINUX_EXTRA_ARGS}}: error copying layers and metadata for container "166e820770389ad80508feef6ff7bc2decc71c5d1171e9d558539de1ade60e00": writing blob: adding layer with blob "sha256:5c7b43d66740b6ec78fbea32eefbc018ddc5e7067cd37bc00b1237fc4b8a27c5": Error processing tar file(exit status 1): write /BambuStudio/deps/build/dep_OCCT-prefix/src/dep_OCCT-build/src/TKShHealing/CMakeFiles/TKShHealing.dir/__/ShapeFix/ShapeFix_ComposeShell.cxx.o: no space left on device
Error: Process completed with exit code 125.

**Comment by abhijitmajumdar** [comment]
> I am going to try https://github.com/actions/runner-images/issues/2840 option with the free runners to see if that works. I'll let you know if I have an update

This worked! I based this change off of @lanewei120's fix for gmp, and it generates an Ubuntu 20.04 appimage as well now. See https://github.com/bambulab/BambuStudio/pull/2042 and the corresponding appimage generated here https://github.com/bambulab/BambuStudio/actions/runs/5550654522. That said, the pipeline takes more than 2hrs to run. Optimizations could really help the build process

**Comment by lanewei120** [comment]
Great!

my previous patch including two fixes:
1. fix the gmp downloading issue
2. change to ubuntu-latest from ubuntu 20.04 to fix the linking issue(https://github.com/actions/runner-images/issues/7908)

I have merged the fix 1 into master just now
for fix-2, as I am still waiting  github team's feedback, and we need to use ubuntu 20.04, it is just a temp debug patch

**Pull request merged**
