### PR TITLE
Add geeetech M1 machine

### PR DESCRIPTION
**Pull request by whoseyoung**
Printing settings for the M1 machine provided by Geeetech officially.

### CODE REVIEW

**Comment by QingZhangBambu** [comment]
There are spaces at the end of the line, please remove it!

**Comment by whoseyoung** [comment]
> There are spaces at the end of the line, please remove it! all files have extra spaces @whoseyoung please check and fix

All issue items processed.

**Comment by QingZhangBambu** [comment]
image
@whoseyoung there should be Direct Drive. please fix it.

**Comment by whoseyoung** [comment]
> There are spaces at the end of the line, please remove it! all files have extra spaces @whoseyoung please check and fix

Thank you for reminding and updated

**Comment by QingZhangBambu** [comment]
@whoseyoung Hi, the extruder type hasn't been fixed, if you want to add this to the 1.10 official version, please update it as fast as possible.

**Comment by whoseyoung** [comment]
> @whoseyoung Hi, the extruder type hasn't been fixed, if you want to add this to the 1.10 official version, please update it as fast as possible.

Please close this PR and I will reapply for another one，tks.

**Comment by whoseyoung** [comment]
> @whoseyoung Hi, the extruder type hasn't been fixed, if you want to add this to the 1.10 official version, please update it as fast as possible.

Already reapplied. Please help to approve PR#5117, thank you

**Pull request closed without merging**
