### PR TITLE
Add support for Bambu Lab X1 series live video stream on Linux

### PR DESCRIPTION
**Pull request by jwise**
This PR adds Linux support for the X1's live video camera.

wxWidgets on Linux uses GStreamer as its back-end for wxMediaCtrl, which doesn't have a bambu: URI handler.  On Windows, this is handled by a Windows Media subsystem plugin, and on Mac, this is handled with a BambuPlayer class.  Luckily, the libBambuSource.so binary that is distributed with the network plugin package already contains support for receiving h.264 data from the network, and the API is the same as is used by the tiny bambusource.exe binary on Windows; we glue this into a GStreamer source plugin that registers a URI handler for bambu:.

To make this work, we make a few additional changes elsewhere.  GStreamer seems to have trouble rendering an Xv overlay onto a 32bpp X visual, but Bambu Slicer seems to request a 32bpp visual for some background transparency in the Notebook; it doesn't seem to use it in an interesting way on Linux, though, so we remove that request for transparency to allow Bambu Studio to render to a 24bpp visual.  The media controller infrastructure also makes a few assumptions about when sizing information can be queried from a wxMediaCtrl backend that do not hold true on Linux; we either fix those assumptions, or fake them out, as needed.  We also make a few changes needed to successfully compile C.

This has only been tested with the GStreamer backend for wxWidgets -- notably, not the GStreamer-play backend (these are, astonishingly, two different things!).  If you find that this seems not to work, consider *un*installing the libgstreamer-plugins-bad1.0-dev package and then rebuilding wxWidgets.  I've also only tested this with my cloud-connected X1 Carbon; I haven't tested this with a P1P or in LAN mode.

image

### CODE REVIEW

**Comment by jwise** [comment]
Note for Bambu team -- if you have any questions about this PR, I am happy to answer here, or if you prefer you can send me a WeChat (my WeChat ID is `jwise0`).

**Comment by lanewei120** [comment]
thanks very much for doing this

we are doing similiar work here, however we have limited progress:)
I am glad to see it works, we will have a try and give the feedback as soon as possible

**Comment by jwise** [comment]
Yeah, I spent more time than I'd like to admit on this.  Probably 20 or 30 hours.  I thought that the GStreamer part was going to be the hard part, and it turned out to be vastly the easy part compared to trying to actually get GStreamer to render something in BBS.

BTW, I think that we probably can use this to implement 'Go Live' without an additional download, as long as the system has `ffmpeg` installed (fairly common on Linux machines).  We can `mkfifo` or something and just write bytes directly from `libBambuSource` inside of BBS into a pipe for `ffmpeg`, rather than having to have a `BambuSource.exe`-analogous binary.  (Though I admit that having `BambuSource.exe` be so clear and simple made it easy for me to understand what I needed to do to implement this into a GStreamer module -- thanks!)

Let me know if you have any questions.  My next project was going to be to see if I could get EGL working, by updating GLEW -- are you already working on that?

**Comment by lanewei120** [comment]
> by updating GLEW -- are you already working on that?

1. for the "Go Live" functions,  we ought to keep this function work even after we close the bambustudio
so, we let the "BambuSource.exe" out of Bambu Studio
2. for the EGL part, we are not working on it
I don't know if disable the EGL setting in wxWidgets, the opengl hardware functions will work or not

**Comment by jwise** [comment]
> for the "Go Live" functions, we ought to keep this function work even after we close the bambustudio

Oh, I see, I understand.  I guess BambuStudio could `fork()` rather than having a separate binary but that's fine too.  Probably the right way to do that is to build a separate `bambusource` binary in cmake somewhere?  Then we can still avoid having to distribute a Linux encoder binary package.

> I don't know if disable the EGL setting in wxWidgets, the opengl hardware functions will work or not

Yes, EGL disabled still uses hardware accel.  Basically the difference between EGL and GLX mode comes down to how a GL context is created (I think EGL takes a slightly more direct path, and is a fair bit more modern).  With EGL disabled, wxWidgets falls back on GLX.  The problem right now, as I understand it, is that the bundled GLEW only supports GLX on Linux, not EGL.

Turning off EGL works for now and should not impact anything (i.e., **the EGL-disable patch as proposed is safe**), but EGL is required if we want to use Wayland instead of the X11 `GDK_BACKEND` in the future.  So we will need to make GLEW support EGL.  I guess I could open a separate bug to track that.

**Comment by deftdawg** [comment]
I get this trying to build.

```
/BambuStudio/src/slic3r/GUI/Printer/gstbambusrc.c:530:32: error: 'bambusrc' undeclared (first use in this function)
  530 |   return GST_ELEMENT_REGISTER (bambusrc, plugin);
      |                                ^~~~~~~~
/BambuStudio/src/slic3r/GUI/Printer/gstbambusrc.c:530:32: note: each undeclared identifier is reported only once for each function it appears in
/BambuStudio/src/slic3r/GUI/Printer/gstbambusrc.c:531:1: error: control reaches end of non-void function [-Werror=return-type]
  531 | }
      | ^
```

**Comment by lanewei120** [comment]
I can build successfully,  however, when click play, it seems can not find h264 decoder

0:00:07.084639639 38076     0x6a41180 DEBUG               basesrc gstbasesrc.c:2102:gst_base_src_default_event:<source> handle event reconfigure event: 0x7ff45001f1d0, time 99:99:99.999999999, seq-num 113, (NULL) 
0:00:07.084772047 38076     0x6a41180 WARN           uridecodebin gsturidecodebin.c:960:unknown_type_cb:<uridecodebin0> warning: 找不到‘video/x-h264, framerate=(fraction)0/1, parsed=(boolean)true, stream-format=(string)avc, width=(int
)1760, height=(int)1080, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, alignment=(string)au, profile=(string)constrained-baseline, level=(string)4, codec_data=(buffer)0142c028ffe1001b6742c0288d8d50370112
f2cd90000003001000000303c8f08846a001000468ce31b2’类型可用的解码器。 
0:00:07.084798957 38076     0x6a41180 WARN              decodebin gstdecodebin2.c:4701:gst_decode_bin_expose:<decodebin0> error: no suitable plugins found: 
Missing decoder: H.264 (Constrained Baseline Profile) (video/x-h264, framerate=(fraction)0/1, parsed=(boolean)true, stream-format=(string)avc, width=(int)1760, height=(int)1080, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-d
epth-chroma=(uint)8, alignment=(string)au, profile=(string)constrained-baseline, level=(string)4, codec_data=(buffer)0142c028ffe1001b6742c0288d8d50370112f2cd90000003001000000303c8f08846a001000468ce31b2) 

0:00:07.084819826 38076     0x6a41180 WARN           uridecodebin gsturidecodebin.c:1027:no_more_pads_full:<uridecodebin0> error: no suitable plugins found: 
../gst/playback/gstdecodebin2.c(4701): gst_decode_bin_expose (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0: 
no suitable plugins found: 
Missing decoder: H.264 (Constrained Baseline Profile) (video/x-h264, framerate=(fraction)0/1, parsed=(boolean)true, stream-format=(string)avc, width=(int)1760, height=(int)1080, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-d
epth-chroma=(uint)8, alignment=(string)au, profile=(string)constrained-baseline, level=(string)4, codec_data=(buffer)0142c028ffe1001b6742c0288d8d50370112f2cd90000003001000000303c8f08846a001000468ce31b2)

**Comment by jwise** [comment]
@deftdawg Were there any other errors further up?  You might be missing the Gstreamer headers entirely.  If not, what version of Gstreamer do you have installed?

@lanewei120 Paste the output of `$ gst-inspect-1.0 | grep 264`?  On my system, it looks like:

```
libav:  avdec_h264: libav H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 decoder
libav:  avenc_h264_omx: libav OpenMAX IL H.264 video encoder encoder
libav:  avmux_ipod: libav iPod H.264 MP4 (MPEG-4 Part 14) muxer
openh264:  openh264dec: OpenH264 video decoder
openh264:  openh264enc: OpenH264 video encoder
rtp:  rtph264depay: RTP H264 depayloader
rtp:  rtph264pay: RTP H264 payloader
typefindfunctions: video/x-h264: h264, x264, 264
uvch264:  uvch264deviceprovider (GstDeviceProviderFactory)
uvch264:  uvch264mjpgdemux: UVC H264 MJPG Demuxer
uvch264:  uvch264src: UVC H264 Source
va:  vah264dec: VA-API H.264 Decoder
vaapi:  vaapih264dec: VA-API H264 decoder
vaapi:  vaapih264enc: VA-API H264 encoder
videoparsersbad:  h264parse: H.264 parser
x264:  x264enc: x264 H.264 Encoder
```

(Try installing the package `gstreamer1.0-libav`, or `gstreamer1.0-vaapi` for hardware acceleration?)

**Comment by deftdawg** [comment]
My bad, yes... There's another error further up where it's failing to get defined...

```
/BambuStudio/src/slic3r/GUI/Printer/gstbambusrc.c:116:39: error: expected ')' before string constant              116 | GST_ELEMENT_REGISTER_DEFINE (bambusrc, "bambusrc",                                                            |                                       ^~~~~~~~~~~                                                             |                                       )         /BambuStudio/src/slic3r/GUI/Printer/gstbambusrc.c: In function 'gst_bambusrc_create':
```

Yeah must be missing some gst lib... Here's what I have atm:
```
dpkg --get-selections | grep gst                                                gir1.2-gst-plugins-base-1.0:amd64               install gir1.2-gstreamer-1.0:amd64                      install
gstreamer1.0-gl:amd64                           install
gstreamer1.0-plugins-base:amd64                 install
gstreamer1.0-plugins-good:amd64                 install
gstreamer1.0-pulseaudio:amd64                   install
gstreamer1.0-x:amd64                            install
libgstreamer-gl1.0-0:amd64                      install
libgstreamer-plugins-base1.0-0:amd64            install
libgstreamer-plugins-base1.0-dev:amd64          install
libgstreamer-plugins-good1.0-0:amd64            install
libgstreamer-plugins-good1.0-dev                install
libgstreamer1.0-0:amd64                         install
libgstreamer1.0-dev:amd64                       install
libgstreamerd-3-0                               install
libgstreamerd-3-dev                             install
```

I'll see if I can sort it out

**Comment by jwise** [comment]
I suspect even further up there is probably a missing include (which one?).  But we probably should have Cmake either make a hard dependency on this, or ifdef it out if Gstreamer is not available.

**Comment by jwise** [comment]
Hooray!  It would be nice to reproduce @deftdawg 's issue and make sure that CMake does the right thing on systems that cannot successfully build with GStreamer.

**Comment by deftdawg** [comment]
Here are steps to reproduce with podman on your branch:
```
# rm build; rm deps/build to have a clean starting point 
nano Containerfile # comment out everything from buildLinux.sh -s and down
podman build . -v $(pwd):/BambuStudio -t bambu-studio-builder  # this will build to deps (-d) 
# start the build container
podman run -v $(pwd):/BambuStudio -it --rm localhost/bambu-studio-builder /bin/bash 
./BuildLinux.sh -s # build slicer inside the container 
```

**Comment by jwise** [comment]
It looks like GST_ELEMENT_REGISTER_DEFINE was added in GStreamer 1.20, but this podman has 1.16.  I will fix this to support GStreamer 1.16.

**Comment by lanewei120** [comment]
it can work on my ubuntu soon

**Comment by deftdawg** [comment]
It probably would compile unmodified on 22.04, however the AppImage is currently built against 20.04 LTS for maximum glibc backwards compatibility.

If it proves too difficult to support 20.04 based building, I'm not opposed to bumping it to 22.04...

**Comment by jwise** [comment]
@deftdawg Please try with commit 0e5dfc6?  That one builds for me inside the podman environment.  Haven't tested it, though.

**Comment by deftdawg** [comment]
Reinstating the other Containerfile steps everything built and the AppImage was produced.

Copied it over to my KDE Neon/22.04LTS machine.   Starts up, but the camera display area is black (doesn't matter if I hit the play button or not, though it does say `Playing...` if I hit it)

Looks like the gst libs are being linked.

```sh
./BambuStudio_ubu64.AppImage --appimage-mount
/tmp/.mount_BambuSpzfYjD
# Second window
cd /tmp/.mount_BambuSpzfYjD
/tmp/.mount_BambuSpzfYjD$ ldd bin/bambu-studio  | grep -i gst
        libgstreamer-1.0.so.0 => /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007f2562d1b000)
        libgstvideo-1.0.so.0 => /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007f2562c56000)
        libgstbase-1.0.so.0 => /lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007f255d5aa000)
        libgstapp-1.0.so.0 => /lib/x86_64-linux-gnu/libgstapp-1.0.so.0 (0x00007f255becc000)
        libgstpbutils-1.0.so.0 => /lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0 (0x00007f255be88000)
        libgstaudio-1.0.so.0 => /lib/x86_64-linux-gnu/libgstaudio-1.0.so.0 (0x00007f255be06000)
        libgsttag-1.0.so.0 => /lib/x86_64-linux-gnu/libgsttag-1.0.so.0 (0x00007f255bdc4000)
        libgstgl-1.0.so.0 => /lib/x86_64-linux-gnu/libgstgl-1.0.so.0 (0x00007f255bd3a000)
        libgstfft-1.0.so.0 => /lib/x86_64-linux-gnu/libgstfft-1.0.so.0 (0x00007f255bd2e000)
        libgstallocators-1.0.so.0 => /lib/x86_64-linux-gnu/libgstallocators-1.0.so.0 (0x00007f2559b74000)

Neon uses X11 on this intel laptop.

Will see if it behaves differently on my HoloISO steamOS install (Arch-based) w/ an AMD GPU...

**Comment by jwise** [comment]
Interesting.  Can you run with the environment variable `GST_DEBUG=3` set?

**Comment by deftdawg** [comment]
It was missing H264, installing `gstreamer1.0-plugins-bad` on the host system fixed it... but I'll have to have a think about how to handle that so the AppImage provides the deps directly:

```sh
sudo apt install -y gstreamer1.0-plugins-bad
```

**Comment by jwise** [comment]
Cool.  I guess it would be nice if wxMediaCtrl could tell us why the pipeline hasn't put itself together properly.  Maybe we can have wxMediaCtrl2 probe for a h.264 decoder element when it initializes the wxMediaCtrl, and if there isn't one, then it should cry?

**Comment by deftdawg** [comment]
> if there isn't one, then it should cry? 

That would be helpful in the interim.

This was the message from the log when it knew:

```sh
0:00:12.804489533 88645 0x7fedcc008d20 WARN            uridecodebin gsturidecodebin.c:960:unknown_type_cb:<uridecodebin0> warning: No decoder available for type 'video/x-h264, framerate=(fraction)0/1, parsed=(boolean)false, stream-format=(string)byte-stream'.
0:00:12.804571139 88645 0x7fedcc008d20 WARN               decodebin gstdecodebin2.c:4701:gst_decode_bin_expose:<decodebin0> error: no suitable plugins found:
Missing decoder: H.264 (video/x-h264, framerate=(fraction)0/1, parsed=(boolean)false, stream-format=(string)byte-stream)

0:00:12.804603948 88645 0x7fedcc008d20 WARN            uridecodebin gsturidecodebin.c:1027:no_more_pads_full:<uridecodebin0> error: no suitable plugins found:
../gst/playback/gstdecodebin2.c(4701): gst_decode_bin_expose (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: H.264 (video/x-h264, framerate=(fraction)0/1, parsed=(boolean)false, stream-format=(string)byte-stream)

0:00:12.804818563 88645 0x7fedcc008d20 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<source> error: Internal data stream error.
0:00:12.804834740 88645 0x7fedcc008d20 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<source> error: streaming stopped, reason not-linked (-1)
```

**Comment by jwise** [comment]
@deftdawg Try 0c9f6b7.

**Comment by deftdawg** [comment]
@jwise very nice... gives a nice warning on my SteamOS PC.

no-h264

Btw, if the printer is offline and the user tries to stream video, gstreamer will wrongfully accept the blame ... Probably not necessary to handle that it's an edge case that only people with crappy wifi will probably get.  :laughing:

offline-printer

**Comment by lanewei120** [comment]
could you exclude the GLEW's commit from this pull request?

we can merge other three patches together

**Comment by jwise** [comment]
Oops.  I think I must have cherry picked that onto my branch while I was working on some of the other stuff.  Removed the GLEW commit, and now pushed the other three.

**Comment by lanewei120** [comment]
thanks very much for doing this

**Comment by lanewei120** [comment]
Hello @jwise 

our P1P uses mjpeg stream instead of H264, as the hardware limitation
and we want to add the mjpeg capability also

should we just add this capability in the same plugin
or need to write a new plugin?

thanks

**Comment by jwise** [comment]
I think the same plugin is the way to do it.  I was trying to figure out how to change the caps of a pad at runtime but I don't really understand how.  I think it involves doing a `gst_event_new_caps` and then a `gst_pad_push_event` to send the caps down to the next element (and probably having to implement a caps query, also).

But it might be easier than that.  Maybe if you just replace `GST_STATIC_CAPS("video/x-h264,framerate=0/1,parsed=(boolean)false,stream-format=(string)byte-stream")` with `GST_STATIC_CAPS_ANY`, then the `playbin` element will figure it out automatically?

**Comment by lanewei120** [comment]
thanks for the reply.

we will try it later

**Comment by jwise** [comment]
I don't have P1P hardware here to test with, but if you get stuck, let me know and I can try to provide some debugging tips.  I designed the plugin so that you can build it outside of the Bambu Studio environment if you need to, though I don't have the command line for it handy and anyway it is past my bedtime :) Running it in a standalone gstreamer pipeline with `gst-play` or `gst-launch` is really useful though, and is how I tested most of it before I tried to merge it into Bambu Studio.

**Comment by lanewei120** [comment]
it is not an urgent task
In fact Tomorrow is Chinese New Year here, we will be on our holidays;
I will try your suggestions after the holiday

thanks very much

**Comment by spuiuk** [comment]
Thank you @jwise,  I a P1P and was wondering why everyone else seems to have their camera working except for me and then saw the later comments on this issue. So I did a quick compile using the following patch on the latest v1.4.2 branch with the following patch as mentioned by you in an earlier comment.

```
diff --git a/src/slic3r/GUI/Printer/gstbambusrc.c b/src/slic3r/GUI/Printer/gstbambusrc.c
index bfde2f57..5f0f9cae 100644
--- a/src/slic3r/GUI/Printer/gstbambusrc.c
+++ b/src/slic3r/GUI/Printer/gstbambusrc.c
@@ -78,7 +78,7 @@ GST_DEBUG_CATEGORY_STATIC (gst_bambusrc_debug);
 static GstStaticPadTemplate srctemplate = GST_STATIC_PAD_TEMPLATE ("src",
     GST_PAD_SRC,
     GST_PAD_ALWAYS,
-    GST_STATIC_CAPS("video/x-h264,framerate=0/1,parsed=(boolean)false,stream-format=(string)byte-stream"));
+    GST_STATIC_CAPS_ANY);
 
 enum
 {
```

This has the video working for me on my P1P.

My repo is available at https://github.com/spuiuk/BambuStudio/tree/test_pip_video
and a test Appimage available at [www.spui.uk/BambuStudio/BambuStudio_F37_v01.04.02.13-5-g5bd2b114.AppImage](www.spui.uk/BambuStudio/BambuStudio_F37_v01.04.02.13-5-g5bd2b114.AppImage)

**Comment by lanewei120** [comment]
@spuiuk 
thanks for doing this

we also verified here, it works for both P1P and X1/X1C

already submitted to v1.4.2 branch

**Comment by jwise** [comment]
I also have a change to make playback more reliable with gstreamer-player.  I will put up a PR for that soon.  Working on other performance stuff right now.

**Pull request merged**
