### PR TITLE
Machine End G-code: Turn off logo lamp when finished

### PR DESCRIPTION
**Pull request by GuzziRaz**
This turns off the toolhead LED after a print job is completed, in all profiles that turned it on at the start of print.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Good! So only changr is turn pff logo part codr the last line? A1?

**Comment by GuzziRaz** [comment]
> Good! So only changr is turn pff logo part codr the last line? A1?

Yeah it's hard to see the effective diff in these files but the actual change is merely adding ` M960 S5 P0 ; turn off logo lamp ` at the very end of Machine Start G-code.

**Comment by Eldenroot** [comment]
Cool thank you!

**Comment by tsmith35** [comment]
lol I submitted the same request for OrcaSlicer and it was rejected. https://github.com/SoftFever/OrcaSlicer/pull/3071

**Comment by XunZhangBambu** [comment]
@GuzziRaz 
Thank you for your submission. However, I believe this behavior is customized, and if it is turned off, the logo will not light up unless printed again. Some users may find it appealing for the logo to remain illuminated consistently

**Pull request closed without merging**
