### PR TITLE
Russian translation update

### PR DESCRIPTION
**Pull request by AndylgTom**
Russian translation update BambuStudio 1.9.0.70 Public Beta 3. 
Improved translation, corrected errors.
Thx.

### CODE REVIEW

**Comment by lanewei120** [comment]
@AndylgTom it seems has conflicts with our master codes
could you rebase to the newest and sove the conflicts?

**Comment by AndylgTom** [comment]
> @AndylgTom thanks for doing this it seems has conflicts with our master codes could you rebase to the newest and sove the conflicts?

I just updated the po file (based on the latest pot file) .
I hope I don't need to create new Pull requests.

**Comment by lanewei120** [comment]
image
you need to do the rebase
and resolve the conflicts

do you use "git rebase" before?

**Comment by AndylgTom** [comment]
Done.

**Comment by lanewei120** [comment]
image
still failed
which commands are you using to solve this conflict?

if still failed, you can create a new pull request
and use a tool such as beyond compare to move the changes from old one to the new one

**Pull request closed without merging**
