### PR TITLE
fix crashes when switching timelapse and vase mode

### PR DESCRIPTION
**Pull request by SoftFever**

### CODE REVIEW

**Comment by SoftFever** [comment]
#1165

**Comment by lanewei120** [comment]
@SoftFever 
thanks very much

I have tried this patch
it still crashes when switch timelapse_mode with boost::any_cast

I just have a debug and commit a patch here
https://github.com/bambulab/BambuStudio/commit/69b884e5851ff2d54f59ed186133925ee6c0845b

Please use this one for a try

**Comment by SoftFever** [comment]
@lanewei120 do you have a project file to repro the crash?

**Comment by lanewei120** [comment]
just a new project is ok

timelapse_crash

**Comment by SoftFever** [comment]
Hmm, I probably have other changes along with this change that fixed the crash in my folk.
You might want to check and test this project as well https://github.com/SoftFever/BambuStudio-SoftFever/issues/175

**Comment by lanewei120** [comment]
yes, with that patch, it should be ok~

we also added a fix here, https://github.com/bambulab/BambuStudio/commit/69b884e5851ff2d54f59ed186133925ee6c0845b
it can fix this issue too:)

I am afraid there will be conflicts, 
we can merge this patch but can not merge that patch now...
anyway, both methods should work

thanks for the submission

**Pull request merged**
